### ISSUE TITLE
sha224 and sha384 support

### ISSUE THREAD

**Issue by ibrokemypie** [nabijaczleweli/checksums#19]
Hey, is it possible to add support for sha224 and sha384? Thanks!

**Comment by nabijaczleweli** [comment]
Do you've any crates that do either of those algorithms? I couldn't find any with a cursory `crates.io` glance…

**Comment by ibrokemypie** [comment]
Found a few: 
https://github.com/andydude/rust-sha/
https://docs.rs/openssl/0.10.12/openssl/sha/index.html
https://docs.rs/sha2/0.8.0/sha2/

**Comment by nabijaczleweli** [comment]
Ah, my dumb arse searched for the algorithms themselves, instead of checking my SHA lib :v

Anyway, check [current `master`](https://github.com/nabijaczleweli/checksums/commit/42a556d8175b44d9473055dac975794be3b6a0f7)?

**Comment by nabijaczleweli** [comment]
@ibrokemypie *cough*

**Comment by nabijaczleweli** [comment]
Released in [`v0.6.0`](https://github.com/nabijaczleweli/checksums/releases/tag/v0.6.0)
