### ISSUE TITLE
Support for CRC32c

### ISSUE THREAD

**Issue by jasonlor** [nabijaczleweli/checksums#20]
Requesting support for CRC32c.

Here are the related crates:
- https://github.com/zowens/crc32c
- https://github.com/BurntSushi/rust-snappy/blob/master/src/crc32.rs

**Comment by nabijaczleweli** [comment]
Thank you for the suggestion!

Released in [`v0.6.0`](https://github.com/nabijaczleweli/checksums/releases/tag/v0.6.0)
