### ISSUE TITLE
Make regex case insensitive

### ISSUE THREAD

**Issue by ghost** [nabijaczleweli/checksums#25]
So yeah in the title. It's seems in docs of regex it's self there's ability to make case-insensitive.
Why insensitive? Because hashes can be both lowercase and uppercase, and when you do a checking of lowercase ones it tells that the only difference is how letters are written.

**Comment by nabijaczleweli** [comment]
`:xdigit:` is already `[0-9A-Fa-f]`, so I don't get what your regex point is. Do you have an example of what doesn't work, but you feel should?

**Comment by ghost** [comment]
hm... idk it tells me other, hang on will post

**Comment by ghost** [comment]
File "ppt-dmmm.001" doesn't match
  Was: 48aa6aef
  Is : 48AA6AEF
File "ppt-dmmm.002" doesn't match
  Was: 2de461d5
  Is : 2DE461D5
File "ppt-dmmm.003" doesn't match
  Was: 61584be9
  Is : 61584BE9
File "ppt-dmmm.004" doesn't match
  Was: 89c9a444
  Is : 89C9A444

Here is the example above.

**Comment by ghost** [comment]
As you see in the file the hashes were lowercase ones, but program tells me that the only difference here are how are they written. In this case it's calculated the uppercase one. As you see it can't tell the difference between them.

**Comment by nabijaczleweli** [comment]
I fail to see how that's regex-related, but can you try the current `master` branch (at least d6448b628ca41e55270b0ee74327598faff7e10a)? Works for me in a trivial testcase.

**Comment by ghost** [comment]
Sure, I will let you know if it works.

**Comment by ghost** [comment]
Works, rn. Thanks.

**Comment by nabijaczleweli** [comment]
Released in [`v0.8.1`](https://github.com/nabijaczleweli/checksums/releases/tag/v0.8.1)
