### ISSUE TITLE
Whirlpool support?

### ISSUE THREAD

**Issue by ghost** [nabijaczleweli/checksums#26]
Well, as states in title. Any chance of getting Whirlpool support?
https://crates.io/crates/whirlpool

**Comment by nabijaczleweli** [comment]
Can you try current `master` branch (at least b6b574ddf79d2c38e5877e5e90848857efd56930) with `-a WHIRLPOOL`?

**Comment by ghost** [comment]
Hell yeah, man. Hang on.

**Comment by ghost** [comment]
Works, but I also change `blake` to `WHIRLPOOL` lol

**Comment by nabijaczleweli** [comment]
I'm assuming you mean in whirpool.rs – good point.

**Comment by nabijaczleweli** [comment]
Released in [`v0.9.0`](https://github.com/nabijaczleweli/checksums/releases/tag/v0.9.0)
